spring:
  application:
    name: lm-integration
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  configuration:
    processor:
      enabled: true
server:
  port: '8087'
app:
  cors:
    allowed-origins: https://cartagenacorporation.com,https://www.cartagenacorporation.com
  jwt:
    secret: ${JWT_SECRET}
project:
  service:
    url: http://localhost:8082/api/projects
issue:
  service:
    url: http://localhost:8090/api/issues
auth:
  service:
    url: http://localhost:8081/api/oauth
gemini:
  api:
    key: ${GEMINI_KEY}
    url: ${GEMINI_URL}
