spring:
  application:
    name: lm-integration
  datasource:
    url: jdbc:postgresql://localhost:5433/lamuralla
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: '8087'
app:
  cors:
    allowed-origins: https://cartagenacorporation.com,https://www.cartagenacorporation.com
  jwt:
    secret: ${JWT_SECRET}
project:
  service:
    url: http://localhost:8082/api/projects
issue:
  service:
    url: http://localhost:8090/api/issues
auth:
  service:
    url: http://localhost:8081/api/oauth
config:
  service:
    url: http://localhost:8088/api/config
organization:
  service:
    url: http://localhost:8091/api/organizations
